language: python

python:
 - 2.7

script:
  - python helloworld.py

after_success:
  - echo "テスト終了!"

notifications:
    slack: h-itg-dev:4z5R67svHYtxSBd3o6dsZHrT
    webhooks:
      urls:
        - http://13.114.123.10:8080/webhook
      on_failure: never # default: always

