language: python

python:
 - 2.7

script:
  - python helloworld.py

after_success:
  - coveralls
  - echo "テスト終了!"
  
notifications:
  slack: h-itg-dev:4z5R67svHYtxSBd3o6dsZHrT
  webhooks:
      - http://13.114.123.10:8080/webhook
      

